### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BlackGhost3** [cloned-doy/whatsfly#3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x584966da]

goroutine 17 [running, locked to thread]:
go.mau.fi/libsignal/state/record.(*State).SenderChainKey(...)
        /home/doy/go/pkg/mod/go.mau.fi/libsignal@v0.1.0/state/record/SessionState.go:297
go.mau.fi/libsignal/session.(*Cipher).Encrypt(0xc0001a71b0, {0xc00115a700, 0x447, 0x700})
        /home/doy/go/pkg/mod/go.mau.fi/libsignal@v0.1.0/session/SessionCipher.go:71 +0x7a
go.mau.fi/whatsmeow.(*Client).encryptMessageForDevice(0xc0001c6800, {0xc001142000, 0x438, 0x438}, {{0xc00157e460, 0xd}, 0x0, 0x0, {0x5886473e, 0xe}, ...}, ...)
        /home/doy/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230226124255-e5c8f3c95d78/send.go:706 +0x67d
go.mau.fi/whatsmeow.(*Client).encryptMessageForDeviceAndWrap(0x7?, {0xc001142000?, 0x1?, 0x3?}, {{0xc00157e460, 0xd}, 0x0, 0x0, {0x5886473e, 0xe}, ...}, ...)
        /home/doy/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230226124255-e5c8f3c95d78/send.go:678 +0x59
go.mau.fi/whatsmeow.(*Client).encryptMessageForDevices(0xc0001c6800, {0x5897aaf0, 0xc00001c0e0}, {0xc001140ea0, 0x4, 0x5897f150?}, {{0xc000187ee0, 0xd}, 0x0, 0x2, ...}, ...)
        /home/doy/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230226124255-e5c8f3c95d78/send.go:662 +0x3ec
go.mau.fi/whatsmeow.(*Client).prepareMessageNode(0x1ee40c50a28?, {0x5897aaf0, 0xc00001c0e0}, {{0xc00157e1b0, 0xd}, 0x0, 0x0, {0x5886473e, 0xe}, 0x0}, ...)
        /home/doy/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230226124255-e5c8f3c95d78/send.go:560 +0x45f
go.mau.fi/whatsmeow.(*Client).sendDM(0xc0001a7ac0?, {0x5897aaf0, 0xc00001c0e0}, {{0xc00157e1b0, 0xd}, 0x0, 0x0, {0x5886473e, 0xe}, 0x0}, ...)
        /home/doy/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230226124255-e5c8f3c95d78/send.go:439 +0x385
go.mau.fi/whatsmeow.(*Client).SendMessage(0xc0001c6800, {0x5897aaf0, 0xc00001c0e0}, {{0xc00157e1b0, 0xd}, 0x0, 0x0, {0x5886473e, 0xe}, 0x0}, ...)
        /home/doy/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230226124255-e5c8f3c95d78/send.go:167 +0x85c
main.SendMessage(0x0?, 0xc000052301?)
        /home/doy/code/whatsfly/whatsfly/dependencies/main.go:104 +0x1d3

**Comment by Labfox** [comment]
This is probably an error woth whatsmeow

**Comment by cloned-doy** [comment]
Check out the latest update!

 Feel free to give it a try and let me know if you encounter any issues.

**Comment by BlackGhost3** [comment]
last time I used it I got band 😂, any work around that ?

**Comment by Labfox** [comment]
If you got banned, you can try the workarounds on this discord server (not the same library but still usefull): [https://discord.gg/HruJaYrUWV](https://discord.gg/HruJaYrUWV)

**Comment by Labfox** [comment]
> last time I used it I got band 😂, any work around that ?

Also you should normally create another issue for that and close this one if resolved
